---
# tasks file for webb
- name: install package
  package:
    name: nginx
    state: latest

- name: install package unzip
  package:
    name: unzip
    state: latest

- name: download template for nginx webserver
  get_url:
    url: https://www.free-css.com/assets/files/free-css-templates/download/page277/intot.zip
    dest: /var/www/html/

- name: Extracting the template for nginx
  unarchive:
    src: /var/www/html/intot.zip
    dest: /var/www/html/
    remote_src: true

- name: start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true 
