- name: setfacts_playbook
  hosts: all
  tasks:
    - name: set fact
      set_fact: URL=["www.google.com","www.igp.com"] city="nagpur"

    - name: print variable
      debug:
        msg: "{{URL}}  {{city}}"
 
